"""user_subscription

Revision ID: 99bc1c4e8e08
Revises: f162d89fcb0b
Create Date: 2023-11-23 14:59:08.130782

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "99bc1c4e8e08"
down_revision = "f162d89fcb0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=False),
        sa.Column("subscription_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_subscription_id"), "user_subscription", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_subscription_id"), table_name="user_subscription")
    op.drop_table("user_subscription")
    # ### end Alembic commands ###
