"""product_categort_delete

Revision ID: c88a155d1dbb
Revises: 4b6a51c13d63
Create Date: 2024-01-27 22:30:47.715040

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c88a155d1dbb"
down_revision = "4b6a51c13d63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "product_composition_category_id_fkey",
        "product_composition",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "product_composition",
        "product_category",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_composition", type_="foreignkey")
    op.create_foreign_key(
        "product_composition_category_id_fkey",
        "product_composition",
        "product_category",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###
