"""user_roles

Revision ID: f162d89fcb0b
Revises: f0c24948bf72
Create Date: 2023-11-22 19:24:48.770015

"""
import sqlalchemy as sa
from alembic import op
from db.models.users import UserRoles

# revision identifiers, used by Alembic.
revision = "f162d89fcb0b"
down_revision = "f0c24948bf72"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_roles_enum_type = sa.Enum(UserRoles, name="user_roles")
    user_roles_enum_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum(UserRoles, name="user_roles"),
            default=UserRoles.USER,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    user_roles_enum_type = sa.Enum(UserRoles, name="user_roles")
    user_roles_enum_type.drop(op.get_bind())
    # ### end Alembic commands ###
