"""fcd_id optional field

Revision ID: f4a13c357e31
Revises: c88a155d1dbb
Create Date: 2024-01-28 13:03:19.516433

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f4a13c357e31"
down_revision = "c88a155d1dbb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_composition", sa.Column("fdc_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_composition", "fdc_id")
    # ### end Alembic commands ###
